apiVersion: v1
kind: Service
metadata:
  name: -svc
  namespace: test-sample_testloy
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: sample_test